### ISSUE TITLE
Feature Roadmap

### ISSUE THREAD

**Issue by eshedmargalit** [eshedmargalit/paperaweek#96]
# Visible
## UX
- [x] Replace 404 with smarter "this user's profile is private" if the target profile exists but not public (#65)
- [x] Draft duplication
- [x] Draft duplication
- [x] Form: drafts don't save when FieldArray fields are deleted (b/c no onBlur event is triggered)
- [x] Actually add form validation with `Yup` -- should require that papers have at least a valid title and one author
- [x] Feature request: dropdown in statistics panel to choose from All Time, Last 6 months, Last 3 months

## Styles
- [x] Continue to Preview button in Form is green, then hovers to green making the text illegible on hover
- [x] Toggle public/private profile is  on `<PublicProfile />` ugly and doesn't work on all screen sizes

# Invisible
- [ ] Start collecting emails on login
- [ ] Move internal `href`s to `<Link>` components (#84)
- [ ] Despite the addition of DTO types, there are still places where a distinction should be made between "pure" types and types-in-database. The flagship example is this one: https://github.com/eshedmargalit/paperaweek/blob/6f59980d9c8d1324ff4183a5b4529b726db9a2df/client/src/components/SearchableReviewDisplay/SearchableReviewDisplay-view.tsx#L109-L124
- [x] Finish writing tests
- [x] Prior to release: database migration
